version: '3'

services:
  comments:
    build: .
    depends_on:
      - 'database'
    ports:
      - '3002:3002'
    env_file:
      - comments-variables.env
      
  database:
    image: mongo:latest
    ports:
      - '27017:27017'